# Configuration options for the currency item
currency:
  # The amount of currency a player obtains upon initially joining the server
  firstJoinAmount: 64
  # The amount of currency a player obtains per week
  weeklyAmount: 64
  # The amount of time (in seconds) the player must play each week to receive currency
  weeklyTime: 7200
  # The amount of time (in seconds) between when players are reminded about their weekly currency
  notifyTime: 900
  # The message to be displayed when a player can claim their currency
  # Use %name% to be the name of the player
  # Use %rewardAmount% to be the amount of currency the player can get
  # Use %rewardClick% to be the click me part of the reward message
  rewardMessage: "&6&l%name%! &eYou have &6%rewardAmount% &ecurrency to claim. %rewardClick% &eto claim the currency!"
  # The click me part of the reward message
  rewardClickMessage: "&b&l&nClick Me&r"
  # The text to show when hovering over the reward message
  rewardHoverMessage: "&2Click Me to claim all your currency. Be sure you have space in your inventory!" 

